ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"

REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}

refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}



#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rhumainedb
    username: smartges
    password: '#LddndAemadn1879#'
#
#  profiles:
#    active: default

  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect





  mail:
    host: smtp.gmail.com
    port: 465
    username: prexedafrica@gmail.com
    password: 'nnltchukwygkeftr'
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          auth: true
          starttls.enable: true
          ssl:
            enable: true
            trust: "*"
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
#
#
#  sql:
#    init:
#      platform: postgres
#      mode: always
#
#
#
#
#
#  logging:
#    level:
#      org.springframework.security: DEBUG
